#!/bin/bash

# The service we want to check or toggle (according to systemctl)
SERVICE=$BLOCK_INSTANCE
# Colors to display
ACTIVE_COLOR=#22BB22
# Exact string to display
ACTIVE="<span foreground=\"$ACTIVE_COLOR\">$SERVICE</span>"

if [ "$( systemctl is-active "$SERVICE" )" != "active" ]
then
  if [ "$BLOCK_BUTTON" == '1' ]
  then
    if systemctl start "$SERVICE"
    then
      echo "$ACTIVE"
    fi
  fi
else
  echo "$ACTIVE"
fi
